# Generated by Django 3.1.2 on 2020-10-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201017_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='customar_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='document',
            name='deadline_date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='deadline_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='work_price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
